import { Inter,Monoton } from 'next/font/google'
import './globals.css'
import Head from 'next/head';

// import "../styles/fonts.css";
require('dotenv').config();

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sachin Verma',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

//   var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
// var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

// // Change the icons inside the button based on previous settings
// if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
//     themeToggleLightIcon.classList.remove('hidden');
// } else {
//     themeToggleDarkIcon.classList.remove('hidden');
// }

// var themeToggleBtn = document.getElementById('theme-toggle');

// themeToggleBtn.addEventListener('click', function() {

//     // toggle icons inside button
//     themeToggleDarkIcon.classList.toggle('hidden');
//     themeToggleLightIcon.classList.toggle('hidden');

//     // if set via local storage previously
//     if (localStorage.getItem('color-theme')) {
//         if (localStorage.getItem('color-theme') === 'light') {
//             document.documentElement.classList.add('dark');
//             localStorage.setItem('color-theme', 'dark');
//         } else {
//             document.documentElement.classList.remove('dark');
//             localStorage.setItem('color-theme', 'light');
//         }

//     // if NOT set via local storage previously
//     } else {
//         if (document.documentElement.classList.contains('dark')) {
//             document.documentElement.classList.remove('dark');
//             localStorage.setItem('color-theme', 'light');
//         } else {
//             document.documentElement.classList.add('dark');
//             localStorage.setItem('color-theme', 'dark');
//         }
//     }
    
// });

  return (
    <html lang="en">
      {/* <a  href="https://icons8.com/icon/62452/firebase">Firebase</a> icon by <a href="https://icons8.com">Icons8</a> */}
      {/* <Head  >
      <script>
    {/* // On page load or when changing themes, best to add inline in `head` to avoid FOUC */}
    {/* if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
        document.documentElement.classList.add('dark')
    } else {
        document.documentElement.classList.remove('dark')
    }
</script> */}
      {/* </Head> */} 
     
      <body className={inter.className}> <main className='dark:bg-[#1d0039] bg-gray-900 '>{children}</main></body>
    </html>
  )
}
